# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
general:
  branches:
    only:
     - test # list of branches to build
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t jwt_test_local .
     - run: docker run -d --name jwt-none-container-test -p 5000:5000 jwt_test_local
     - run: docker container ls
     - run: sleep 6
     - run: docker exec -it jwt-none-container-test pytest
