# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker run -d --name jwt-none-container-test -p 5000:5000 nicolanov/jwt_none:master
     - run: docker container ls
     #- run: docker exec -it jwt-none-container-test pytest
