name: ci

on:
  pull_request:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: nicolanov/jwt_none:pr
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
