name: ci

on:
  push:
    branches: test
  pull_request:
    branches: test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Pytest
        uses: addnab/docker-run-action@v1
        with:
          image: nicolanov/jwt_none:test
          run: |
            sleep 6
            pytest
